#!/usr/bin/env python3
"""
Interactive helper to create or update the local .env file used for dbt.

It prompts for Databricks connection details and writes them to the project root.
Secrets are captured via getpass so the token does not echo to the terminal.
"""

from pathlib import Path
import getpass


BASE_DIR = Path(__file__).resolve().parents[1]
ENV_PATH = BASE_DIR / ".env"


def prompt_value(label: str, default: str | None = None, secret: bool = False) -> str:
    """Prompt the user for a value, optionally with a default or hidden input."""
    suffix = f" [{default}]" if default else ""
    prompt = f"{label}{suffix}: "
    if secret:
        value = getpass.getpass(prompt)
    else:
        value = input(prompt)

    value = value.strip()
    if not value and default is not None:
        return default
    return value


def main() -> None:
    print("This utility will create or update the project .env file for local dbt runs.")
    if ENV_PATH.exists():
        confirmation = input(
            f"An existing .env file was found at {ENV_PATH}. Overwrite it? [y/N]: "
        ).strip().lower()
        if confirmation != "y":
            print("Aborting; existing .env left unchanged.")
            return

    host = prompt_value("DATABRICKS_HOST")
    http_path = prompt_value("DATABRICKS_HTTP_PATH")
    token = prompt_value("DATABRICKS_TOKEN", secret=True)
    org_id = prompt_value("DATABRICKS_ORG_ID (optional)", default="")

    lines = [
        "# Generated by scripts/create_env.py for local dbt configuration",
        f"DATABRICKS_HOST={host}",
        f"DATABRICKS_HTTP_PATH={http_path}",
        f"DATABRICKS_TOKEN={token}",
    ]

    if org_id:
        lines.append(f"DATABRICKS_ORG_ID={org_id}")
    else:
        lines.append("# DATABRICKS_ORG_ID=")

    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote credentials to {ENV_PATH}. Keep this file out of version control.")


if __name__ == "__main__":
    main()


